version: '3.8'
services:
  backend:
    build: ./reserva-hotel-backend
    ports:
      - "3000:3000"
    volumes:
      - ./reserva-hotel-backend/.env:/app/.env
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: nest_user
      POSTGRES_PASSWORD: nest_pass
      POSTGRES_DB: nest_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db_data:
